package net.simplifiedcoding.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_HOME = "home"
const val ROUTE_PROFILE = "profile"
const val ROUTE_SPLASH = "splash"
const val ROUTE_LEAFY = "leafy"
const val ROUTE_BUTTERFLY = "butterfly"
const val ROUTE_SPACEY = "unreal"
const val ROUTE_SCENERY = "scenery"
const val ROUTE_TEARDROP = "teardrop"
const val ROUTE_SEASIDE = "seaside"
const val ROUTE_SEAVIEW = "seaview"
const val ROUTE_ADVENT = "adventuretime"
const val ROUTE_ANIM = "anime"
const val ROUTE_BEAUTI = "beautiful"
const val ROUTE_BIKE = "bike"
const val ROUTE_MILES = "miles"
const val ROUTE_NATURE = "nature"
const val ROUTE_SPIDEY = "spidey"
const val ROUTE_TAT = "tat"
const val ROUTE_VIEW = "view"
const val ROUTE_FISHER = "fisherman"
